//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onity.HT24.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Onity.HT24.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device did not reply the ENQ command..
        /// </summary>
        internal static string BusyDevice {
            get {
                return ResourceManager.GetString("BusyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Message not acknowledged due LRC checksum error.
        /// </summary>
        internal static string ChecksumError {
            get {
                return ResourceManager.GetString("ChecksumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single opening cards sold out. They can only edit 4 unique opening cards per room and client. If you ask to edit more, this error message is generated..
        /// </summary>
        internal static string EA {
            get {
                return ResourceManager.GetString("EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhausted timing. The recorder/reader cancels the
        ///operation in progress if you can not swallow the card..
        /// </summary>
        internal static string ED {
            get {
                return ResourceManager.GetString("ED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetic format error. The card has been recorded following other rules (Usually this error will occur when wanting to read on track 3 according to ISO standards a card recorded according to ONITY standards) or the magnetic strip is defective..
        /// </summary>
        internal static string EF {
            get {
                return ResourceManager.GetString("EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level error. The card has been recorded at too low a level. (Dirt on the head of the recorder or low quality card)..
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in magnetic track. Card inserted backwards or missing magnetic track..
        /// </summary>
        internal static string EP {
            get {
                return ResourceManager.GetString("EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sintaxe error. The message is incorrect (unknown command, parameters
        ///incorrect, prohibited characters or too many characters in
        ///recording according to ISO standards, etc. ...).
        /// </summary>
        internal static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuck card. The card does not comply with the physical measurements required.
        /// </summary>
        internal static string ET {
            get {
                return ResourceManager.GetString("ET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;{0}&quot; returned an invalid reply &quot;{1}&quot;.
        /// </summary>
        internal static string InvalidReply {
            get {
                return ResourceManager.GetString("InvalidReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No answer from addressed recorder/reader. Failure communications, shutdown or does not exist..
        /// </summary>
        internal static string NC {
            get {
                return ResourceManager.GetString("NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files. Interface PC files damaged or not found.
        /// </summary>
        internal static string NF {
            get {
                return ResourceManager.GetString("NF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room out of service. You can not record the
        ///card until the room is back in service
        ///indicating it in the HT24 program..
        /// </summary>
        internal static string OS {
            get {
                return ResourceManager.GetString("OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overflow. The addressed recorder/reader has not finished the previous task..
        /// </summary>
        internal static string OV {
            get {
                return ResourceManager.GetString("OV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown card. By sending a card to a room that you do not exists..
        /// </summary>
        internal static string TD {
            get {
                return ResourceManager.GetString("TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error code &quot;{0}&quot;.
        /// </summary>
        internal static string UnknownErrorCode {
            get {
                return ResourceManager.GetString("UnknownErrorCode", resourceCulture);
            }
        }
    }
}
